shinyUI(fluidPage(
        headerPanel("Could you please beat Chelsea?"),
        sidebarPanel(
                dataTableOutput('lTable')
        ),
        mainPanel(
                tabsetPanel(
                        tabPanel("League Mixture",
                                 h3("Uses of this Application"),
                                 p("This application is designed to calculate how 
                                   many points current Premier League leaders, 
                                   Chelsea, will end up on by the end of the season. Others team need how many points to win the league."),
                                 p("The things you need to predict the result for 
                                   each of Chelsea's remaining fixtures on the 
                                   Remaining Fixtures tab. Then click on the End 
                                   of Season to know points require by other team to win the league."),
                                 p("On the left side We can see the current league 
                                   standings as of 05/03/16")),
                        tabPanel("Remaining Fixtures",
                                 radioButtons("southampton", "16/02 - Chelsea vs Southampton",
                                              c("Chelsea Win" = "win",
                                                "Draw" = "draw",
                                                "Chelsea Loss" = "loss"), inline=TRUE),
                                 radioButtons("hull", "22/02 - Hull vs Chelsea",
                                              c("Chelsea Win" = "win",
                                                "Draw" = "draw",
                                                "Chelsea Loss" = "loss"), inline=TRUE),
                                 radioButtons("stoke", "04/01 - Chelsea vs Stoke",
                                              c("Chelsea Win" = "win",
                                                "Draw" = "draw",
                                                "Chelsea Loss" = "loss"), inline=TRUE),
                                 radioButtons("qpr", "12/01 - QPR vs Chelsea",
                                              c("Chelsea Win" = "win",
                                                "Draw" = "draw",
                                                "Chelsea Loss" = "loss"), inline=TRUE),
                                 radioButtons("manutd", "18/02 - Chelsea vs Man Utd",
                                              c("Chelsea Win" = "win",
                                                "Draw" = "draw",
                                                "Chelsea Loss" = "loss"), inline=TRUE),
                                 radioButtons("arsenal", "26/01 - Arsenal vs Chelsea",
                                              c("Chelsea Win" = "win",
                                                "Draw" = "draw",
                                                "Chelsea Loss" = "loss"), inline=TRUE),
                                 radioButtons("leicester", "29/01 - Leicester vs Chelsea",
                                              c("Chelsea Win" = "win",
                                                "Draw" = "draw",
                                                "Chelsea Loss" = "loss"), inline=TRUE),
                                 radioButtons("crystalpalace", "02/01 - Chelsea vs Crystal Palace",
                                              c("Chelsea Win" = "win",
                                                "Draw" = "draw",
                                                "Chelsea Loss" = "loss"), inline=TRUE),
                                 radioButtons("liverpool", "09/01 - Chelsea vs Liverpool",
                                              c("Chelsea Win" = "win",
                                                "Draw" = "draw",
                                                "Chelsea Loss" = "loss"), inline=TRUE),
                                 radioButtons("westbrom", "16/02 - West Brom vs Chelsea",
                                              c("Chelsea Win" = "win",
                                                "Draw" = "draw",
                                                "Chelsea Loss" = "loss"), inline=TRUE),
                                 radioButtons("sunderland", "24/01 - Chelsea vs Sunderland",
                                              c("Chelsea Win" = "win",
                                                "Draw" = "draw",
                                                "Chelsea Loss" = "loss"), inline=TRUE)),
                        tabPanel("End of Season", 
                                 textOutput("totalPoints"),
                                 textOutput("manCityRequire"),
                                 textOutput("arsenalRequire"),
                                 textOutput("manUtdRequire"),
                                 textOutput("liverpoolRequire"),
                                 textOutput("spursRequire"),
                                 textOutput("southamptonRequire"),
                                 textOutput("stokeRequire"),
                                 textOutput("swanseaRequire"),
                                 textOutput("westHamRequire"),
                                 textOutput("newcastleRequire"),
                                 textOutput("crystalPalaceRequire"),
                                 textOutput("westBromRequire"),
                                 textOutput("evertonRequire"),
                                 textOutput("hullRequire"),
                                 textOutput("sunderlandRequire"),
                                 textOutput("astonVillaRequire"),
                                 textOutput("qprRequire"),
                                 textOutput("burnleyRequire"),
                                 textOutput("leicesterRequire")
                )
        )
)))